name = "SolarFunctions"
uuid = "fe378e5d-cdbf-458e-9372-6c90f6cdeed2"
version = "0.1.0"
authors = ["Nicola Mignoni"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
Dates = "1.11.0"
Pkg = "1.12.0"
Serialization = "1.11.0"
Test = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
